# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharesentry',
            old_name='P_id',
            new_name='PersonName',
        ),
        migrations.RenameField(
            model_name='sharesentry',
            old_name='Id',
            new_name='SharesID',
        ),
        migrations.RenameField(
            model_name='sharesentry',
            old_name='U_id',
            new_name='UserName',
        ),
    ]
