# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 13:01
from __future__ import unicode_literals

import Expenses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_auto_20180912_1801'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expensetype', '0002_auto_20180912_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesEntry',
            fields=[
                ('ExpensesId', models.AutoField(primary_key=True, serialize=False)),
                ('Exp_Amt', models.FloatField()),
                ('Exp_Img', models.ImageField(blank=True, null=True, upload_to=Expenses.models.upload_file)),
                ('Exp_date', models.DateField(verbose_name='ExpenseDate')),
                ('Exp_comm', models.TextField()),
                ('Exp_Type_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensetype.ExpenseType')),
                ('PersonName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
