# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetype',
            old_name='id',
            new_name='ExpenseType_id',
        ),
    ]
