# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
        ('investmtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentsEntry',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Inv_Init_Amt', models.FloatField(verbose_name='Init Amnt')),
                ('Inv_Mat_Amt', models.FloatField(verbose_name='Mature Amnt')),
                ('Inv_ROI_PerYear', models.FloatField(verbose_name='ROI in Percentage')),
                ('Inv_Date', models.DateField(verbose_name='Inv Date')),
                ('Inv_Mat_Date', models.DateField(verbose_name='Inv Mat Date')),
                ('Inv_Due_Date', models.DateField(verbose_name='Inv Due Date')),
                ('Inv_Img', models.ImageField(blank=True, null=True, upload_to='')),
                ('Inv_comm', models.TextField()),
                ('InvestType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmtype.InvestTypes')),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
