# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 12:36
from __future__ import unicode_literals

import Investment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investment', '0003_auto_20180914_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentsentry',
            name='Inv_Img',
            field=models.ImageField(blank=True, null=True, upload_to=Investment.models.upload_file),
        ),
    ]
