# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
        ('earningtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsEntry',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ear_Amt', models.FloatField()),
                ('Ear_Img', models.BinaryField(null=True)),
                ('Ear_FileName', models.CharField(max_length=300, null=True, verbose_name='FileName')),
                ('Ear_date', models.DateField(verbose_name='ExpenseDate')),
                ('Ear_comm', models.TextField()),
                ('Earning_Type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earningtype.EarningTypes')),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
