# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earnings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsentry',
            name='Ear_FileName',
        ),
        migrations.AlterField(
            model_name='earningsentry',
            name='Ear_Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
