# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Earnings', '0002_auto_20180907_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earningsentry',
            old_name='Earning_Type_id',
            new_name='Earning_Type_Name',
        ),
        migrations.RenameField(
            model_name='earningsentry',
            old_name='Id',
            new_name='EarningsId',
        ),
        migrations.RenameField(
            model_name='earningsentry',
            old_name='P_id',
            new_name='PersonName',
        ),
        migrations.RenameField(
            model_name='earningsentry',
            old_name='U_id',
            new_name='UserName',
        ),
    ]
