# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 19:39
from __future__ import unicode_literals

import Earnings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earnings', '0003_auto_20180912_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsentry',
            name='Ear_Img',
            field=models.ImageField(blank=True, null=True, upload_to=Earnings.models.upload_file),
        ),
    ]
