# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import persons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=30, verbose_name="person's first name")),
                ('Person_Image', models.ImageField(blank=True, null=True, upload_to=persons.models.upload_file)),
                ('Person_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=1)),
                ('Person_BDate', models.DateField()),
                ('Person_CDate', models.DateField(auto_now_add=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
