# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('None', 'N')], max_length=1),
        ),
    ]
