# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20180807_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=5),
        ),
    ]
