# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20180808_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Person_Image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
