# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_person_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_Image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
