# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20180816_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_Image',
            field=models.ImageField(blank=True, null=True, upload_to=persons.models.upload_file),
        ),
    ]
