# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EarningTypeName', models.CharField(max_length=30, verbose_name="Earning's Type")),
                ('EarningType_CDate', models.DateField(auto_now_add=True)),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
