# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earningtype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earningtypes',
            old_name='id',
            new_name='EarnType_id',
        ),
        migrations.RenameField(
            model_name='earningtypes',
            old_name='U_id',
            new_name='User_id',
        ),
    ]
